<script setup lang="ts">
const phases = [
 {n:'01',title:'Autoaprendizaje',subtitle:'Investigación individual',items:[
  {q:'¿Cómo influyen las 5V de Big Data en el diseño y desempeño?',goal:'Conectar cada V con una decisión técnica, no limitarse a definirlas.',must:'Volumen→almacenamiento/cómputo; velocidad→streaming/latencia; variedad→esquema y features; veracidad→calidad; valor→métrica empresarial.',guide:'Construye una tabla de cinco filas: problema, impacto sobre recomendaciones, tecnología y métrica. Cierra explicando los compromisos entre latencia, costo y calidad.',example:'80 M de usuarios generan clics en tiempo real: Kafka absorbe velocidad, Spark resume historial y una política de calidad filtra bots.',criteria:'5V aplicadas (40%) · decisiones justificadas (30%) · ejemplo cuantificado (20%) · conclusión (10%).'},
  {q:'¿En qué se diferencian contenido, colaborativo e híbrido?',goal:'Elegir por escenario empresarial y evidencia disponible.',must:'Fuente de señales, cold start, diversidad, explicabilidad, costo y frecuencia de compra.',guide:'Compara en una matriz y resuelve tres casos: catálogo editorial, marketplace y viajes. No declares un ganador universal.',example:'Una agencia de viajes usa conocimiento por restricciones; un streaming combina colaboración y contenido.',criteria:'Comparación técnica (35%) · selección contextual (30%) · límites (20%) · claridad (15%).'},
  {q:'¿Qué funciones cumplen Hadoop, Spark, Kafka y Flink?',goal:'Ubicar cada tecnología dentro de una arquitectura extremo a extremo.',must:'Hadoop: histórico; Spark: batch/ML; Kafka: log de eventos; Flink: streaming con estado.',guide:'Dibuja el recorrido clic→evento→features→candidatos→ranking. Para cada bloque indica entrada, salida, estado y tolerancia a fallos.',example:'Kafka recibe “producto visto”; Flink actualiza afinidad; Spark reentrena embeddings nocturnos sobre el data lake.',criteria:'Responsabilidades correctas (40%) · flujo coherente (30%) · tiempo real vs batch (20%) · diagrama (10%).'},
  {q:'¿Qué algoritmos ML/DL mejoran precisión y resuelven cold start o escala?',goal:'Relacionar algoritmo, supuesto, señal y limitación.',must:'Factorización, vecinos, modelos supervisados, embeddings, secuenciales y contenido.',guide:'Escoge tres algoritmos. Explica datos de entrada, predicción, complejidad y qué problema mitiga. Señala qué no resuelve.',example:'Embeddings de descripción permiten representar un producto nuevo; no solucionan un usuario sin preferencias.',criteria:'Mecanismo (35%) · relación con desafío (30%) · limitaciones (20%) · comparación (15%).'},
  {q:'Investigue un caso de éxito empresarial medible.',goal:'Separar afirmaciones comerciales de evidencia verificable.',must:'Problema, arquitectura pública, métrica, línea base, periodo, fuente y posibles factores de confusión.',guide:'Utiliza fuentes primarias cuando existan. Distingue “usa recomendaciones” de “las recomendaciones causaron X”. Incluye limitaciones de la evidencia.',example:'Un A/B test con conversión y retención es evidencia más fuerte que una cifra corporativa sin metodología.',criteria:'Calidad de fuentes (30%) · métrica contextualizada (25%) · análisis técnico (25%) · crítica causal (20%).'}
 ]},
 {n:'02',title:'Discusión',subtitle:'Debate crítico grupal',items:[
  {q:'¿Qué sistema conviene a un e-commerce con millones de usuarios?',goal:'Defender una arquitectura, no solo nombrar “híbrido”.',must:'Dos etapas, cold start, inventario, latencia, diversidad y métricas.',guide:'Propón candidato + ranking + re-ranking. El grupo contrario debe identificar un cuello de botella y una falla ética.',example:'Contenido cubre ítems nuevos; colaboración explota conducta; reglas impiden recomendar productos sin stock.',criteria:'Arquitectura (35%) · escala (25%) · contraargumentos (20%) · métricas (20%).'},
  {q:'¿Personalización o riesgo para la privacidad?',goal:'Razonar proporcionalidad: beneficio, necesidad y alternativa menos invasiva.',must:'Consentimiento, minimización, finalidad, retención, seguridad e inferencias sensibles.',guide:'Debatan desde empresa, usuario y regulador. Definan qué dato no recolectarían aunque mejore el CTR.',example:'Ubicación precisa permanente es desproporcionada si basta una zona aproximada durante la sesión.',criteria:'Perspectivas (30%) · principios (30%) · salvaguardas (25%) · postura (15%).'},
  {q:'¿Qué cambia usando tecnología tradicional en vez de Big Data?',goal:'Evitar afirmar que “tradicional” siempre falla; identificar umbrales.',must:'Throughput, latencia, partición, costo, disponibilidad y complejidad operativa.',guide:'Comparen un catálogo pequeño y uno global. Indiquen cuándo una base relacional sigue siendo suficiente y cuándo aparece el cuello.',example:'Un comercio local puede precalcular recomendaciones SQL; 80 M usuarios en evento masivo requieren distribución.',criteria:'Comparación contextual (40%) · umbrales (25%) · costos (20%) · conclusión (15%).'},
  {q:'¿Cómo afecta la baja calidad de datos?',goal:'Trazar el error desde captura hasta decisión empresarial.',must:'Duplicados, bots, identidad compartida, eventos faltantes, leakage y deriva.',guide:'Construyan un árbol causal: defecto→feature→ranking→conducta→KPI. Añadan controles preventivos y detectivos.',example:'Cuenta familiar mezcla gustos; el perfil resultante reduce relevancia y sesga el reentrenamiento.',criteria:'Cadena causal (35%) · controles (30%) · impacto empresarial (20%) · ejemplo (15%).'},
  {q:'¿Qué explica el éxito o límite del caso investigado?',goal:'Integrar factores tecnológicos, organizacionales y estratégicos.',must:'Datos, talento, experimentación, integración, incentivos, gobernanza y experiencia del usuario.',guide:'Clasifiquen factores en necesarios, diferenciadores y riesgos. Expliquen por qué copiar solo el algoritmo no reproduce el éxito.',example:'Sin cultura de A/B testing no se sabe si un modelo más preciso genera retención.',criteria:'Visión integral (40%) · causalidad prudente (25%) · evidencia (20%) · síntesis (15%).'}
 ]},
 {n:'03',title:'Reflexión',subtitle:'Síntesis grupal',items:[
  {q:'¿Por qué mejoran competitividad y experiencia?',goal:'Expresar valor sin caer en determinismo tecnológico.',must:'Reducción de búsqueda, descubrimiento, conversión, fidelización y riesgos de saturación.',guide:'Redacta tesis, mecanismo, ejemplo, condición de éxito y límite. Conecta valor del usuario y de la empresa.',example:'Descubrir un ítem relevante aporta valor mutuo; insistir en lo popular puede degradar confianza.',criteria:'Tesis (25%) · mecanismo (30%) · equilibrio (25%) · ejemplo (20%).'},
  {q:'Diseñe un recomendador para una empresa peruana.',goal:'Proponer una solución viable para contexto local.',must:'Empresa, usuarios, datos, consentimiento, algoritmo, stack, métricas, conectividad y presupuesto.',guide:'Incluye MVP y evolución. Justifica por qué cada tecnología es necesaria; no uses Hadoop/Kafka por moda.',example:'Retail regional: reglas + contenido al inicio; eventos en Kafka solo al superar volumen y necesidad real-time.',criteria:'Contexto peruano (20%) · coherencia (35%) · viabilidad (25%) · riesgos (20%).'},
  {q:'¿Qué aprendizajes resuelven problemas reales?',goal:'Convertir conceptos en principios transferibles.',must:'Señal no equivale a preferencia; métrica offline no equivale a negocio; precisión no basta; datos cambian.',guide:'Elijan tres principios. Para cada uno indiquen una mala decisión que evita y una práctica concreta.',example:'Monitorear drift evita conservar indefinidamente un perfil histórico obsoleto.',criteria:'Profundidad (35%) · transferencia (30%) · prácticas (20%) · claridad (15%).'},
  {q:'¿Qué desafíos éticos, legales y tecnológicos abordar?',goal:'Diseñar gobernanza operativa, no una lista abstracta.',must:'Privacidad, sesgo, transparencia, seguridad, derechos, monitoreo y responsables.',guide:'Elabora registro de riesgos con probabilidad, impacto, dueño, control, evidencia y frecuencia de revisión.',example:'Sesgo de exposición: medir cobertura por proveedor y reservar exploración para ítems relevantes poco visibles.',criteria:'Cobertura (30%) · controles verificables (35%) · responsables (20%) · priorización (15%).'},
  {q:'¿Cómo aplicaría esto en transformación digital?',goal:'Articular una contribución profesional concreta y medible.',must:'Problema, stakeholders, datos, arquitectura, experimento, despliegue, monitoreo y valor estratégico.',guide:'Presenta un mini business case: hipótesis, MVP de ocho semanas, KPI primario, guardrails y decisión de continuar.',example:'Reducir abandono mediante recomendaciones complementarias, vigilando margen, devoluciones y diversidad.',criteria:'Plan ejecutable (35%) · medición (25%) · arquitectura (20%) · responsabilidad (20%).'}
 ]}
]
</script>
<template>
 <section class="page topic13-activities">
  <header class="activities-header"><div><span class="eyebrow">ACTIVIDAD DE APRENDIZAJE · DESARROLLO GUIADO</span><h1>De la consigna a una <em>respuesta defendible.</em></h1><p>Las 15 preguntas originales incluyen objetivo, conceptos obligatorios, ruta de desarrollo, ejemplo y rúbrica. Abre cada actividad y úsala como guía, no como respuesta para copiar.</p></div><a class="outline-button" href="/[13-1]%20BDA%20-%20Clase.pdf" target="_blank">Consultar PDF ↗</a></header>
  <nav class="phase-nav"><a v-for="p in phases" :key="p.n" :href="'#t13-'+p.n"><span>{{p.n}}</span>{{p.title}}</a></nav>
  <section v-for="p in phases" :id="'t13-'+p.n" :key="p.n" class="activity-phase"><div class="phase-heading"><span>{{p.n}}</span><div><span class="eyebrow">{{p.subtitle}}</span><h2>{{p.title}}</h2></div></div>
   <details v-for="(a,i) in p.items" :key="a.q" class="activity-item t13-activity">
    <summary><span>{{String(i+1).padStart(2,'0')}}</span><strong>{{a.q}}</strong><b>+</b></summary>
    <div class="t13-activity-body"><section><span>OBJETIVO COGNITIVO</span><p>{{a.goal}}</p></section><section><span>CONCEPTOS OBLIGATORIOS</span><p>{{a.must}}</p></section><section class="wide"><span>GUÍA PASO A PASO</span><p>{{a.guide}}</p></section><section class="example"><span>EJEMPLO ORIENTADOR</span><p>{{a.example}}</p></section><section class="rubric"><span>CRITERIOS DE EVALUACIÓN</span><p>{{a.criteria}}</p></section><div class="wide answer-tip">Plantilla final: tesis breve → mecanismo técnico → evidencia/ejemplo → alternativa o límite → conclusión vinculada al caso.</div></div>
   </details>
  </section>
 </section>
</template>
