<script setup lang="ts">
import { computed, ref } from 'vue'
const questions=[
 {q:'Un producto nuevo tiene descripción rica pero cero interacciones. ¿Qué estrategia reduce mejor el cold start?',o:['Solo filtrado colaborativo','Representación de contenido y exploración controlada','Eliminar el producto','Esperar compras'],c:1,e:'Los atributos permiten ubicar el ítem antes de recibir interacciones; la exploración recoge evidencia sin exponerlo indiscriminadamente.'},
 {q:'¿Por qué una matriz usuario–ítem suele ser dispersa?',o:['Cada usuario interactúa con una fracción mínima del catálogo','Todos califican todo','No existen productos','La matriz contiene solo texto'],c:0,e:'El catálogo crece mucho más que la capacidad de consumo individual; la mayoría de celdas queda sin observar.'},
 {q:'La factorización de matrices busca:',o:['Duplicar la matriz','Aproximar usuarios e ítems mediante factores latentes de baja dimensión','Aplicar reglas legales','Ordenar alfabéticamente'],c:1,e:'El producto de vectores latentes aproxima preferencias y generaliza sobre celdas no observadas.'},
 {q:'¿Qué papel distingue mejor Kafka de Flink?',o:['Kafka transporta/persiste eventos; Flink calcula continuamente con estado','Ambos son bases OLTP idénticas','Flink solo almacena PDFs','Kafka entrena redes'],c:0,e:'Kafka es un log distribuido; Flink consume flujos, mantiene estado y produce resultados derivados.'},
 {q:'Un aumento offline de Precision@10 garantiza más ventas:',o:['Siempre','Solo con millones de datos','No; requiere validación online y métricas de protección','Sí, si usa deep learning'],c:2,e:'El histórico tiene sesgo de exposición y la métrica proxy puede no causar valor empresarial.'},
 {q:'Recomendar solo éxitos populares produce principalmente:',o:['Mayor serendipia','Sesgo de popularidad y menor cobertura','Cold start resuelto','Privacidad diferencial'],c:1,e:'Los ítems ya expuestos acumulan interacción y refuerzan su visibilidad, formando un bucle.'},
 {q:'¿Qué diferencia novedad de serendipia?',o:['Son idénticas','Novedad es poco conocido; serendipia además es inesperada y útil','Serendipia es irrelevante','Novedad siempre es popular'],c:1,e:'Una recomendación desconocida puede no sorprender; serendipia combina sorpresa, utilidad y cierta distancia del perfil obvio.'},
 {q:'Una cuenta familiar compartida afecta sobre todo:',o:['Veracidad e identidad de las señales','Volumen de discos','Número de productos','Sintaxis SQL'],c:0,e:'El sistema mezcla preferencias de personas distintas y aprende un perfil inconsistente.'},
 {q:'¿Qué arquitectura sirve millones de ítems con baja latencia?',o:['Puntuar exhaustivamente todo por petición','Generar pocos candidatos y después rankearlos','No usar caché ni índices','Un único archivo local'],c:1,e:'La recuperación reduce el espacio; un modelo más costoso ordena solo cientos o miles de candidatos.'},
 {q:'El concept drift ocurre cuando:',o:['Se rompe un disco','Cambia la relación entre señales históricas y preferencias actuales','Se agrega RAM','La matriz es cuadrada'],c:1,e:'Intereses y contexto evolucionan; ventanas, decaimiento y reentrenamiento ayudan a adaptarse.'},
 {q:'¿Por qué un híbrido no es automáticamente superior?',o:['Porque contenido y colaboración no pueden mezclarse','Añade complejidad, latencia y fallos; debe demostrar mejora incremental','Porque no usa datos','Porque carece de algoritmos'],c:1,e:'Cada componente debe justificar su costo mediante experimentación y observabilidad.'},
 {q:'¿Qué explicación de una recomendación es más confiable?',o:['Una frase persuasiva inventada','Una razón derivada fielmente de señales o reglas reales','“La IA lo decidió”','Ocultar el criterio'],c:1,e:'Interpretabilidad exige fidelidad al mecanismo, no solo texto plausible.'},
]
const index=ref(0),answers=ref<(number|null)[]>(Array(questions.length).fill(null)),finished=ref(false)
const score=computed(()=>answers.value.reduce<number>((s,a,i)=>s+(a===questions[i].c?1:0),0))
function reset(){answers.value=Array(questions.length).fill(null);index.value=0;finished.value=false}
</script>
<template>
 <section class="page topic13-quiz"><header class="page-header"><span class="eyebrow">EVALUACIÓN · DIFICULTAD ALTA</span><h1>Quiz de <em>recomendación.</em></h1><p>Arquitectura, algoritmos, Big Data, métricas y riesgos.</p></header>
  <div v-if="!finished" class="t14-quiz-card"><div class="quiz-top"><div><span class="eyebrow">PREGUNTA {{index+1}} DE {{questions.length}}</span><h2>Razonamiento aplicado</h2></div><strong>{{Math.round((index+1)/questions.length*100)}}%</strong></div><div class="quiz-progress"><span :style="{width:((index+1)/questions.length*100)+'%'}"></span></div><h3>{{questions[index].q}}</h3><div class="quiz-options"><button v-for="(o,i) in questions[index].o" :key="o" :class="{selected:answers[index]===i}" @click="answers[index]=i"><span>{{String.fromCharCode(65+i)}}</span><strong>{{o}}</strong></button></div><Transition name="instant-feedback"><div v-if="answers[index]!==null" class="instant-feedback" :class="answers[index]===questions[index].c?'is-correct':'is-wrong'"><strong>{{answers[index]===questions[index].c?'✓ Correcto':'✕ Revisa el razonamiento'}}</strong><p>{{questions[index].e}}</p></div></Transition><div class="quiz-nav"><button :disabled="index===0" @click="index--">← Anterior</button><div></div><button v-if="index<questions.length-1" :disabled="answers[index]===null" @click="index++">Siguiente →</button><button v-else class="finish" :disabled="answers.some(a=>a===null)" @click="finished=true">Finalizar</button></div></div>
  <div v-else class="topic14-results"><span class="eyebrow">RESULTADO</span><h1>{{score}} / {{questions.length}}</h1><p>{{score>=10?'Dominio sólido para examen avanzado.':score>=8?'Buen nivel; revisa las explicaciones falladas.':'Repasa arquitectura, desafíos y métricas.'}}</p><button class="outline-button" @click="reset">Reintentar</button><details v-for="(q,i) in questions" :key="q.q" :class="answers[i]===q.c?'correct':'wrong'"><summary><span>{{answers[i]===q.c?'✓':'✕'}}</span><strong>{{q.q}}</strong></summary><p>{{q.e}}</p></details></div>
 </section>
</template>
